// Generated by CoffeeScript 1.8.0
(function() {
  var async, redis;

  redis = require('./redis');

  async = require('async');

  exports.setToken = function(token) {
    return redis.set("miwifi_token", token, function(err, res) {
      return console.log(err, res);
    });
  };

  exports.getToken = function(cb) {
    return redis.get('miwifi_token', function(err, res) {
      if (err) {
        return cb(err);
      }
      return cb(null, res);
    });
  };

  exports.addDevices = function(devices) {
    return devices.forEach(function(device) {
      var key, _results;
      _results = [];
      for (key in device) {
        redis.exists(key, function(err, res) {
          if (!res) {
            return redis.hmset(key, {
              ip: device[key].ip,
              origin_name: device[key].origin_name
            }, function(err, row) {
              return console.log(err, row);
            });
          } else {
            return console.log("find", key);
          }
        });
        _results.push(redis.exists('deviceSet', function(err, res) {
          if (!res) {
            return redis.sadd('deviceSet', key);
          }
        }));
      }
      return _results;
    });
  };

}).call(this);

//# sourceMappingURL=redis_fun.js.map
