// Generated by CoffeeScript 1.8.0
(function() {
  var Redis, redis;

  Redis = require('ioredis');

  redis = new Redis();

  module.exports = redis;

}).call(this);

//# sourceMappingURL=redis.js.map
